version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      prefix: "chore(deps): :pushpin:"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      non-breaking-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      nextjs-ecosystem:
        patterns:
          - "next*"
          - "react*"
          - "@next/*"
        update-types:
          - "major"
      mdx-ecosystem:
        patterns:
          - "*mdx*"
          - "remark-*"
          - "rehype-*"
        update-types:
          - "major"
      styling-packages:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"
          - "tw-*"
        update-types:
          - "major"
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
        update-types:
          - "major"
      dev-tooling:
        patterns:
          - "@biomejs/*"
          - "babel-*"
        update-types:
          - "major"